name: Bitcoin Miner

on:
  workflow_dispatch:

jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Install and build dependencies
        run: |
          sudo apt-get install make libcurl4-openssl-dev
          wget https://github.com/pooler/cpuminer/releases/download/v2.5.1/pooler-cpuminer-2.5.1.tar.gz
tar xzf pooler-cpuminer-*.tar.gz
          cd cpuminer-*
          ./configure CFLAGS="-O3"
          make
          ls
          ls ..